### ISSUE TITLE
Get MVP site up and running.

### ISSUE THREAD

**Issue by akkshaylawrence** [akkshaylawrence/akkshay-netlify#1]
Get the MVP site up and running

- [ ] Home page that looks simple but nice (search for designs or make one).
- [ ] Header like https://mxstbr.com/
- [ ] A way to get user feedback.
